package com.observability.lab.shared.grpc;

import io.grpc.Metadata;

/**
 * The metadata keys that carry identity across a gRPC hop.
 *
 * <p><strong>gRPC metadata is the HTTP/2 header set.</strong> These are the same names the HTTP path
 * uses in {@link com.observability.lab.shared.correlation.CorrelationHeaders}, lower-cased because
 * HTTP/2 requires it — which is also why {@code traceparent} crosses the protocol boundary with no
 * translation layer at all, and why the OpenTelemetry agent needs no configuration to propagate it.
 *
 * <p>Renaming one of these changes the wire contract between the services, so they are treated as
 * public API in exactly the way the log field names are.
 */
public final class GrpcMetadataKeys {

    /** Per-business-transaction identifier. Preserved unchanged across every hop. */
    public static final Metadata.Key<String> CORRELATION_ID = ascii("x-correlation-id");

    /** Per-call identifier. Generated by the server when the caller does not supply one. */
    public static final Metadata.Key<String> REQUEST_ID = ascii("x-request-id");

    /**
     * Which service made this call. New with gRPC, and it earns its place.
     *
     * <p>Over REST the caller is inferable from the network path. A gRPC channel is long-lived and
     * client-side balanced, so several callers share indistinguishable connection patterns and the
     * peer address identifies a host rather than a service. Making the caller explicit is what lets
     * the provider answer "who is generating this load" from its own logs and metrics, without
     * having to correlate against a trace first.
     */
    public static final Metadata.Key<String> CALLER_SERVICE = ascii("x-caller-service");

    /**
     * The end user's bearer token, relayed by the caller.
     *
     * <p>In metadata rather than in a request field, deliberately: interceptors handle it uniformly,
     * and it never reaches a message log. A token as a protobuf field is a token in every payload
     * dump anyone ever takes.
     */
    public static final Metadata.Key<String> AUTHORIZATION = ascii("authorization");

    /** W3C trace context. Injected by the OpenTelemetry agent; named here for documentation. */
    public static final Metadata.Key<String> TRACEPARENT = ascii("traceparent");

    private GrpcMetadataKeys() {
        throw new AssertionError("No instances.");
    }

    private static Metadata.Key<String> ascii(String name) {
        return Metadata.Key.of(name, Metadata.ASCII_STRING_MARSHALLER);
    }
}
